---
name: AnyEvent-CacheDNS
version: 0.03
author:
  - 'Emmanuel Rodriguez <potyl@cpan.org>'
abstract: Simple DNS resolver with caching
license: perl
build_requires:
  File::Spec::Functions: 0
  Test::More: 0
requires:
  AnyEvent: 0
  perl: v5.6.1
configure_requires:
  File::Spec::Functions: 0
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  AnyEvent::CacheDNS:
    file: lib/AnyEvent/CacheDNS.pm
    version: 0.03
resources:
  bugtracker: http://github.com/potyl/perl-AnyEvent-CacheDNS/issues
  homepage: http://github.com/potyl/perl-AnyEvent-CacheDNS
  license: http://dev.perl.org/licenses/
  repository: http://github.com/potyl/perl-AnyEvent-CacheDNS
